// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MmAnywhere.proto

package org.ratatosk.mmrest.data;

public final class MmAnywhere {
  private MmAnywhere() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum MmPropertyTypes
      implements com.google.protobuf.ProtocolMessageEnum {
    UNDEFINED(0, 0),
    BOOLEAN(1, 1),
    INTEGER(2, 2),
    FLOAT(3, 3),
    STRING(4, 4),
    ;
    
    public static final int UNDEFINED_VALUE = 0;
    public static final int BOOLEAN_VALUE = 1;
    public static final int INTEGER_VALUE = 2;
    public static final int FLOAT_VALUE = 3;
    public static final int STRING_VALUE = 4;
    
    
    public final int getNumber() { return value; }
    
    public static MmPropertyTypes valueOf(int value) {
      switch (value) {
        case 0: return UNDEFINED;
        case 1: return BOOLEAN;
        case 2: return INTEGER;
        case 3: return FLOAT;
        case 4: return STRING;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<MmPropertyTypes>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MmPropertyTypes>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MmPropertyTypes>() {
            public MmPropertyTypes findValueByNumber(int number) {
              return MmPropertyTypes.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.ratatosk.mmrest.data.MmAnywhere.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final MmPropertyTypes[] VALUES = {
      UNDEFINED, BOOLEAN, INTEGER, FLOAT, STRING, 
    };
    
    public static MmPropertyTypes valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private MmPropertyTypes(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:org.ratatosk.mmrest.data.MmPropertyTypes)
  }
  
  public interface MmDevicesListingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .org.ratatosk.mmrest.data.MmDeviceListing mmDeviceListings = 1;
    java.util.List<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing> 
        getMmDeviceListingsList();
    org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing getMmDeviceListings(int index);
    int getMmDeviceListingsCount();
    java.util.List<? extends org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListingOrBuilder> 
        getMmDeviceListingsOrBuilderList();
    org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListingOrBuilder getMmDeviceListingsOrBuilder(
        int index);
  }
  public static final class MmDevicesListing extends
      com.google.protobuf.GeneratedMessage
      implements MmDevicesListingOrBuilder {
    // Use MmDevicesListing.newBuilder() to construct.
    private MmDevicesListing(Builder builder) {
      super(builder);
    }
    private MmDevicesListing(boolean noInit) {}
    
    private static final MmDevicesListing defaultInstance;
    public static MmDevicesListing getDefaultInstance() {
      return defaultInstance;
    }
    
    public MmDevicesListing getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ratatosk.mmrest.data.MmAnywhere.internal_static_org_ratatosk_mmrest_data_MmDevicesListing_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ratatosk.mmrest.data.MmAnywhere.internal_static_org_ratatosk_mmrest_data_MmDevicesListing_fieldAccessorTable;
    }
    
    // repeated .org.ratatosk.mmrest.data.MmDeviceListing mmDeviceListings = 1;
    public static final int MMDEVICELISTINGS_FIELD_NUMBER = 1;
    private java.util.List<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing> mmDeviceListings_;
    public java.util.List<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing> getMmDeviceListingsList() {
      return mmDeviceListings_;
    }
    public java.util.List<? extends org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListingOrBuilder> 
        getMmDeviceListingsOrBuilderList() {
      return mmDeviceListings_;
    }
    public int getMmDeviceListingsCount() {
      return mmDeviceListings_.size();
    }
    public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing getMmDeviceListings(int index) {
      return mmDeviceListings_.get(index);
    }
    public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListingOrBuilder getMmDeviceListingsOrBuilder(
        int index) {
      return mmDeviceListings_.get(index);
    }
    
    private void initFields() {
      mmDeviceListings_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getMmDeviceListingsCount(); i++) {
        if (!getMmDeviceListings(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < mmDeviceListings_.size(); i++) {
        output.writeMessage(1, mmDeviceListings_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < mmDeviceListings_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, mmDeviceListings_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ratatosk.mmrest.data.MmAnywhere.internal_static_org_ratatosk_mmrest_data_MmDevicesListing_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ratatosk.mmrest.data.MmAnywhere.internal_static_org_ratatosk_mmrest_data_MmDevicesListing_fieldAccessorTable;
      }
      
      // Construct using org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMmDeviceListingsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (mmDeviceListingsBuilder_ == null) {
          mmDeviceListings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          mmDeviceListingsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing.getDescriptor();
      }
      
      public org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing getDefaultInstanceForType() {
        return org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing.getDefaultInstance();
      }
      
      public org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing build() {
        org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing buildPartial() {
        org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing result = new org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing(this);
        int from_bitField0_ = bitField0_;
        if (mmDeviceListingsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            mmDeviceListings_ = java.util.Collections.unmodifiableList(mmDeviceListings_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.mmDeviceListings_ = mmDeviceListings_;
        } else {
          result.mmDeviceListings_ = mmDeviceListingsBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing) {
          return mergeFrom((org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing other) {
        if (other == org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing.getDefaultInstance()) return this;
        if (mmDeviceListingsBuilder_ == null) {
          if (!other.mmDeviceListings_.isEmpty()) {
            if (mmDeviceListings_.isEmpty()) {
              mmDeviceListings_ = other.mmDeviceListings_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMmDeviceListingsIsMutable();
              mmDeviceListings_.addAll(other.mmDeviceListings_);
            }
            onChanged();
          }
        } else {
          if (!other.mmDeviceListings_.isEmpty()) {
            if (mmDeviceListingsBuilder_.isEmpty()) {
              mmDeviceListingsBuilder_.dispose();
              mmDeviceListingsBuilder_ = null;
              mmDeviceListings_ = other.mmDeviceListings_;
              bitField0_ = (bitField0_ & ~0x00000001);
              mmDeviceListingsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMmDeviceListingsFieldBuilder() : null;
            } else {
              mmDeviceListingsBuilder_.addAllMessages(other.mmDeviceListings_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getMmDeviceListingsCount(); i++) {
          if (!getMmDeviceListings(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.Builder subBuilder = org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMmDeviceListings(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .org.ratatosk.mmrest.data.MmDeviceListing mmDeviceListings = 1;
      private java.util.List<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing> mmDeviceListings_ =
        java.util.Collections.emptyList();
      private void ensureMmDeviceListingsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          mmDeviceListings_ = new java.util.ArrayList<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing>(mmDeviceListings_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.Builder, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListingOrBuilder> mmDeviceListingsBuilder_;
      
      public java.util.List<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing> getMmDeviceListingsList() {
        if (mmDeviceListingsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mmDeviceListings_);
        } else {
          return mmDeviceListingsBuilder_.getMessageList();
        }
      }
      public int getMmDeviceListingsCount() {
        if (mmDeviceListingsBuilder_ == null) {
          return mmDeviceListings_.size();
        } else {
          return mmDeviceListingsBuilder_.getCount();
        }
      }
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing getMmDeviceListings(int index) {
        if (mmDeviceListingsBuilder_ == null) {
          return mmDeviceListings_.get(index);
        } else {
          return mmDeviceListingsBuilder_.getMessage(index);
        }
      }
      public Builder setMmDeviceListings(
          int index, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing value) {
        if (mmDeviceListingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMmDeviceListingsIsMutable();
          mmDeviceListings_.set(index, value);
          onChanged();
        } else {
          mmDeviceListingsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMmDeviceListings(
          int index, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.Builder builderForValue) {
        if (mmDeviceListingsBuilder_ == null) {
          ensureMmDeviceListingsIsMutable();
          mmDeviceListings_.set(index, builderForValue.build());
          onChanged();
        } else {
          mmDeviceListingsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMmDeviceListings(org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing value) {
        if (mmDeviceListingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMmDeviceListingsIsMutable();
          mmDeviceListings_.add(value);
          onChanged();
        } else {
          mmDeviceListingsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMmDeviceListings(
          int index, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing value) {
        if (mmDeviceListingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMmDeviceListingsIsMutable();
          mmDeviceListings_.add(index, value);
          onChanged();
        } else {
          mmDeviceListingsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMmDeviceListings(
          org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.Builder builderForValue) {
        if (mmDeviceListingsBuilder_ == null) {
          ensureMmDeviceListingsIsMutable();
          mmDeviceListings_.add(builderForValue.build());
          onChanged();
        } else {
          mmDeviceListingsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMmDeviceListings(
          int index, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.Builder builderForValue) {
        if (mmDeviceListingsBuilder_ == null) {
          ensureMmDeviceListingsIsMutable();
          mmDeviceListings_.add(index, builderForValue.build());
          onChanged();
        } else {
          mmDeviceListingsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMmDeviceListings(
          java.lang.Iterable<? extends org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing> values) {
        if (mmDeviceListingsBuilder_ == null) {
          ensureMmDeviceListingsIsMutable();
          super.addAll(values, mmDeviceListings_);
          onChanged();
        } else {
          mmDeviceListingsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMmDeviceListings() {
        if (mmDeviceListingsBuilder_ == null) {
          mmDeviceListings_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          mmDeviceListingsBuilder_.clear();
        }
        return this;
      }
      public Builder removeMmDeviceListings(int index) {
        if (mmDeviceListingsBuilder_ == null) {
          ensureMmDeviceListingsIsMutable();
          mmDeviceListings_.remove(index);
          onChanged();
        } else {
          mmDeviceListingsBuilder_.remove(index);
        }
        return this;
      }
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.Builder getMmDeviceListingsBuilder(
          int index) {
        return getMmDeviceListingsFieldBuilder().getBuilder(index);
      }
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListingOrBuilder getMmDeviceListingsOrBuilder(
          int index) {
        if (mmDeviceListingsBuilder_ == null) {
          return mmDeviceListings_.get(index);  } else {
          return mmDeviceListingsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListingOrBuilder> 
           getMmDeviceListingsOrBuilderList() {
        if (mmDeviceListingsBuilder_ != null) {
          return mmDeviceListingsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mmDeviceListings_);
        }
      }
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.Builder addMmDeviceListingsBuilder() {
        return getMmDeviceListingsFieldBuilder().addBuilder(
            org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.getDefaultInstance());
      }
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.Builder addMmDeviceListingsBuilder(
          int index) {
        return getMmDeviceListingsFieldBuilder().addBuilder(
            index, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.getDefaultInstance());
      }
      public java.util.List<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.Builder> 
           getMmDeviceListingsBuilderList() {
        return getMmDeviceListingsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.Builder, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListingOrBuilder> 
          getMmDeviceListingsFieldBuilder() {
        if (mmDeviceListingsBuilder_ == null) {
          mmDeviceListingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.Builder, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListingOrBuilder>(
                  mmDeviceListings_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          mmDeviceListings_ = null;
        }
        return mmDeviceListingsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.ratatosk.mmrest.data.MmDevicesListing)
    }
    
    static {
      defaultInstance = new MmDevicesListing(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.ratatosk.mmrest.data.MmDevicesListing)
  }
  
  public interface MmDeviceListingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string deviceId = 1;
    boolean hasDeviceId();
    String getDeviceId();
    
    // required string deviceLabel = 2;
    boolean hasDeviceLabel();
    String getDeviceLabel();
    
    // required string deviceType = 3;
    boolean hasDeviceType();
    String getDeviceType();
    
    // required string deviceUrl = 4;
    boolean hasDeviceUrl();
    String getDeviceUrl();
    
    // repeated .org.ratatosk.mmrest.data.MmDeviceProperty mmDeviceProperties = 5;
    java.util.List<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty> 
        getMmDevicePropertiesList();
    org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty getMmDeviceProperties(int index);
    int getMmDevicePropertiesCount();
    java.util.List<? extends org.ratatosk.mmrest.data.MmAnywhere.MmDevicePropertyOrBuilder> 
        getMmDevicePropertiesOrBuilderList();
    org.ratatosk.mmrest.data.MmAnywhere.MmDevicePropertyOrBuilder getMmDevicePropertiesOrBuilder(
        int index);
  }
  public static final class MmDeviceListing extends
      com.google.protobuf.GeneratedMessage
      implements MmDeviceListingOrBuilder {
    // Use MmDeviceListing.newBuilder() to construct.
    private MmDeviceListing(Builder builder) {
      super(builder);
    }
    private MmDeviceListing(boolean noInit) {}
    
    private static final MmDeviceListing defaultInstance;
    public static MmDeviceListing getDefaultInstance() {
      return defaultInstance;
    }
    
    public MmDeviceListing getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ratatosk.mmrest.data.MmAnywhere.internal_static_org_ratatosk_mmrest_data_MmDeviceListing_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ratatosk.mmrest.data.MmAnywhere.internal_static_org_ratatosk_mmrest_data_MmDeviceListing_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string deviceId = 1;
    public static final int DEVICEID_FIELD_NUMBER = 1;
    private java.lang.Object deviceId_;
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string deviceLabel = 2;
    public static final int DEVICELABEL_FIELD_NUMBER = 2;
    private java.lang.Object deviceLabel_;
    public boolean hasDeviceLabel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getDeviceLabel() {
      java.lang.Object ref = deviceLabel_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceLabel_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceLabelBytes() {
      java.lang.Object ref = deviceLabel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        deviceLabel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string deviceType = 3;
    public static final int DEVICETYPE_FIELD_NUMBER = 3;
    private java.lang.Object deviceType_;
    public boolean hasDeviceType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDeviceType() {
      java.lang.Object ref = deviceType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceTypeBytes() {
      java.lang.Object ref = deviceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        deviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string deviceUrl = 4;
    public static final int DEVICEURL_FIELD_NUMBER = 4;
    private java.lang.Object deviceUrl_;
    public boolean hasDeviceUrl() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDeviceUrl() {
      java.lang.Object ref = deviceUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          deviceUrl_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDeviceUrlBytes() {
      java.lang.Object ref = deviceUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        deviceUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .org.ratatosk.mmrest.data.MmDeviceProperty mmDeviceProperties = 5;
    public static final int MMDEVICEPROPERTIES_FIELD_NUMBER = 5;
    private java.util.List<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty> mmDeviceProperties_;
    public java.util.List<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty> getMmDevicePropertiesList() {
      return mmDeviceProperties_;
    }
    public java.util.List<? extends org.ratatosk.mmrest.data.MmAnywhere.MmDevicePropertyOrBuilder> 
        getMmDevicePropertiesOrBuilderList() {
      return mmDeviceProperties_;
    }
    public int getMmDevicePropertiesCount() {
      return mmDeviceProperties_.size();
    }
    public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty getMmDeviceProperties(int index) {
      return mmDeviceProperties_.get(index);
    }
    public org.ratatosk.mmrest.data.MmAnywhere.MmDevicePropertyOrBuilder getMmDevicePropertiesOrBuilder(
        int index) {
      return mmDeviceProperties_.get(index);
    }
    
    private void initFields() {
      deviceId_ = "";
      deviceLabel_ = "";
      deviceType_ = "";
      deviceUrl_ = "";
      mmDeviceProperties_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceLabel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDeviceUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getMmDevicePropertiesCount(); i++) {
        if (!getMmDeviceProperties(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDeviceLabelBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDeviceTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDeviceUrlBytes());
      }
      for (int i = 0; i < mmDeviceProperties_.size(); i++) {
        output.writeMessage(5, mmDeviceProperties_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDeviceIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDeviceLabelBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDeviceTypeBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDeviceUrlBytes());
      }
      for (int i = 0; i < mmDeviceProperties_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, mmDeviceProperties_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ratatosk.mmrest.data.MmAnywhere.internal_static_org_ratatosk_mmrest_data_MmDeviceListing_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ratatosk.mmrest.data.MmAnywhere.internal_static_org_ratatosk_mmrest_data_MmDeviceListing_fieldAccessorTable;
      }
      
      // Construct using org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMmDevicePropertiesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        deviceId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceLabel_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceType_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (mmDevicePropertiesBuilder_ == null) {
          mmDeviceProperties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          mmDevicePropertiesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.getDescriptor();
      }
      
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing getDefaultInstanceForType() {
        return org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.getDefaultInstance();
      }
      
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing build() {
        org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing buildPartial() {
        org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing result = new org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.deviceLabel_ = deviceLabel_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.deviceType_ = deviceType_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deviceUrl_ = deviceUrl_;
        if (mmDevicePropertiesBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            mmDeviceProperties_ = java.util.Collections.unmodifiableList(mmDeviceProperties_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.mmDeviceProperties_ = mmDeviceProperties_;
        } else {
          result.mmDeviceProperties_ = mmDevicePropertiesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing) {
          return mergeFrom((org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing other) {
        if (other == org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (other.hasDeviceLabel()) {
          setDeviceLabel(other.getDeviceLabel());
        }
        if (other.hasDeviceType()) {
          setDeviceType(other.getDeviceType());
        }
        if (other.hasDeviceUrl()) {
          setDeviceUrl(other.getDeviceUrl());
        }
        if (mmDevicePropertiesBuilder_ == null) {
          if (!other.mmDeviceProperties_.isEmpty()) {
            if (mmDeviceProperties_.isEmpty()) {
              mmDeviceProperties_ = other.mmDeviceProperties_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureMmDevicePropertiesIsMutable();
              mmDeviceProperties_.addAll(other.mmDeviceProperties_);
            }
            onChanged();
          }
        } else {
          if (!other.mmDeviceProperties_.isEmpty()) {
            if (mmDevicePropertiesBuilder_.isEmpty()) {
              mmDevicePropertiesBuilder_.dispose();
              mmDevicePropertiesBuilder_ = null;
              mmDeviceProperties_ = other.mmDeviceProperties_;
              bitField0_ = (bitField0_ & ~0x00000010);
              mmDevicePropertiesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getMmDevicePropertiesFieldBuilder() : null;
            } else {
              mmDevicePropertiesBuilder_.addAllMessages(other.mmDeviceProperties_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDeviceId()) {
          
          return false;
        }
        if (!hasDeviceLabel()) {
          
          return false;
        }
        if (!hasDeviceType()) {
          
          return false;
        }
        if (!hasDeviceUrl()) {
          
          return false;
        }
        for (int i = 0; i < getMmDevicePropertiesCount(); i++) {
          if (!getMmDeviceProperties(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              deviceLabel_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              deviceType_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              deviceUrl_ = input.readBytes();
              break;
            }
            case 42: {
              org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.Builder subBuilder = org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addMmDeviceProperties(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string deviceId = 1;
      private java.lang.Object deviceId_ = "";
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      void setDeviceId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
      }
      
      // required string deviceLabel = 2;
      private java.lang.Object deviceLabel_ = "";
      public boolean hasDeviceLabel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getDeviceLabel() {
        java.lang.Object ref = deviceLabel_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          deviceLabel_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceLabel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        deviceLabel_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceLabel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        deviceLabel_ = getDefaultInstance().getDeviceLabel();
        onChanged();
        return this;
      }
      void setDeviceLabel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        deviceLabel_ = value;
        onChanged();
      }
      
      // required string deviceType = 3;
      private java.lang.Object deviceType_ = "";
      public boolean hasDeviceType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDeviceType() {
        java.lang.Object ref = deviceType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          deviceType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        deviceType_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        deviceType_ = getDefaultInstance().getDeviceType();
        onChanged();
        return this;
      }
      void setDeviceType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        deviceType_ = value;
        onChanged();
      }
      
      // required string deviceUrl = 4;
      private java.lang.Object deviceUrl_ = "";
      public boolean hasDeviceUrl() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getDeviceUrl() {
        java.lang.Object ref = deviceUrl_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          deviceUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDeviceUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deviceUrl_ = value;
        onChanged();
        return this;
      }
      public Builder clearDeviceUrl() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deviceUrl_ = getDefaultInstance().getDeviceUrl();
        onChanged();
        return this;
      }
      void setDeviceUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        deviceUrl_ = value;
        onChanged();
      }
      
      // repeated .org.ratatosk.mmrest.data.MmDeviceProperty mmDeviceProperties = 5;
      private java.util.List<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty> mmDeviceProperties_ =
        java.util.Collections.emptyList();
      private void ensureMmDevicePropertiesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          mmDeviceProperties_ = new java.util.ArrayList<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty>(mmDeviceProperties_);
          bitField0_ |= 0x00000010;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.Builder, org.ratatosk.mmrest.data.MmAnywhere.MmDevicePropertyOrBuilder> mmDevicePropertiesBuilder_;
      
      public java.util.List<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty> getMmDevicePropertiesList() {
        if (mmDevicePropertiesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(mmDeviceProperties_);
        } else {
          return mmDevicePropertiesBuilder_.getMessageList();
        }
      }
      public int getMmDevicePropertiesCount() {
        if (mmDevicePropertiesBuilder_ == null) {
          return mmDeviceProperties_.size();
        } else {
          return mmDevicePropertiesBuilder_.getCount();
        }
      }
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty getMmDeviceProperties(int index) {
        if (mmDevicePropertiesBuilder_ == null) {
          return mmDeviceProperties_.get(index);
        } else {
          return mmDevicePropertiesBuilder_.getMessage(index);
        }
      }
      public Builder setMmDeviceProperties(
          int index, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty value) {
        if (mmDevicePropertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMmDevicePropertiesIsMutable();
          mmDeviceProperties_.set(index, value);
          onChanged();
        } else {
          mmDevicePropertiesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setMmDeviceProperties(
          int index, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.Builder builderForValue) {
        if (mmDevicePropertiesBuilder_ == null) {
          ensureMmDevicePropertiesIsMutable();
          mmDeviceProperties_.set(index, builderForValue.build());
          onChanged();
        } else {
          mmDevicePropertiesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addMmDeviceProperties(org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty value) {
        if (mmDevicePropertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMmDevicePropertiesIsMutable();
          mmDeviceProperties_.add(value);
          onChanged();
        } else {
          mmDevicePropertiesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addMmDeviceProperties(
          int index, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty value) {
        if (mmDevicePropertiesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMmDevicePropertiesIsMutable();
          mmDeviceProperties_.add(index, value);
          onChanged();
        } else {
          mmDevicePropertiesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addMmDeviceProperties(
          org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.Builder builderForValue) {
        if (mmDevicePropertiesBuilder_ == null) {
          ensureMmDevicePropertiesIsMutable();
          mmDeviceProperties_.add(builderForValue.build());
          onChanged();
        } else {
          mmDevicePropertiesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addMmDeviceProperties(
          int index, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.Builder builderForValue) {
        if (mmDevicePropertiesBuilder_ == null) {
          ensureMmDevicePropertiesIsMutable();
          mmDeviceProperties_.add(index, builderForValue.build());
          onChanged();
        } else {
          mmDevicePropertiesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllMmDeviceProperties(
          java.lang.Iterable<? extends org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty> values) {
        if (mmDevicePropertiesBuilder_ == null) {
          ensureMmDevicePropertiesIsMutable();
          super.addAll(values, mmDeviceProperties_);
          onChanged();
        } else {
          mmDevicePropertiesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearMmDeviceProperties() {
        if (mmDevicePropertiesBuilder_ == null) {
          mmDeviceProperties_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          mmDevicePropertiesBuilder_.clear();
        }
        return this;
      }
      public Builder removeMmDeviceProperties(int index) {
        if (mmDevicePropertiesBuilder_ == null) {
          ensureMmDevicePropertiesIsMutable();
          mmDeviceProperties_.remove(index);
          onChanged();
        } else {
          mmDevicePropertiesBuilder_.remove(index);
        }
        return this;
      }
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.Builder getMmDevicePropertiesBuilder(
          int index) {
        return getMmDevicePropertiesFieldBuilder().getBuilder(index);
      }
      public org.ratatosk.mmrest.data.MmAnywhere.MmDevicePropertyOrBuilder getMmDevicePropertiesOrBuilder(
          int index) {
        if (mmDevicePropertiesBuilder_ == null) {
          return mmDeviceProperties_.get(index);  } else {
          return mmDevicePropertiesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.ratatosk.mmrest.data.MmAnywhere.MmDevicePropertyOrBuilder> 
           getMmDevicePropertiesOrBuilderList() {
        if (mmDevicePropertiesBuilder_ != null) {
          return mmDevicePropertiesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(mmDeviceProperties_);
        }
      }
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.Builder addMmDevicePropertiesBuilder() {
        return getMmDevicePropertiesFieldBuilder().addBuilder(
            org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.getDefaultInstance());
      }
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.Builder addMmDevicePropertiesBuilder(
          int index) {
        return getMmDevicePropertiesFieldBuilder().addBuilder(
            index, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.getDefaultInstance());
      }
      public java.util.List<org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.Builder> 
           getMmDevicePropertiesBuilderList() {
        return getMmDevicePropertiesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.Builder, org.ratatosk.mmrest.data.MmAnywhere.MmDevicePropertyOrBuilder> 
          getMmDevicePropertiesFieldBuilder() {
        if (mmDevicePropertiesBuilder_ == null) {
          mmDevicePropertiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty, org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.Builder, org.ratatosk.mmrest.data.MmAnywhere.MmDevicePropertyOrBuilder>(
                  mmDeviceProperties_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          mmDeviceProperties_ = null;
        }
        return mmDevicePropertiesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.ratatosk.mmrest.data.MmDeviceListing)
    }
    
    static {
      defaultInstance = new MmDeviceListing(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.ratatosk.mmrest.data.MmDeviceListing)
  }
  
  public interface MmDevicePropertyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string propertyId = 1;
    boolean hasPropertyId();
    String getPropertyId();
    
    // required string propertyValue = 2;
    boolean hasPropertyValue();
    String getPropertyValue();
    
    // required string propertyLabel = 3;
    boolean hasPropertyLabel();
    String getPropertyLabel();
    
    // required string propertyType = 4;
    boolean hasPropertyType();
    String getPropertyType();
    
    // required string propertyUrl = 5;
    boolean hasPropertyUrl();
    String getPropertyUrl();
  }
  public static final class MmDeviceProperty extends
      com.google.protobuf.GeneratedMessage
      implements MmDevicePropertyOrBuilder {
    // Use MmDeviceProperty.newBuilder() to construct.
    private MmDeviceProperty(Builder builder) {
      super(builder);
    }
    private MmDeviceProperty(boolean noInit) {}
    
    private static final MmDeviceProperty defaultInstance;
    public static MmDeviceProperty getDefaultInstance() {
      return defaultInstance;
    }
    
    public MmDeviceProperty getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ratatosk.mmrest.data.MmAnywhere.internal_static_org_ratatosk_mmrest_data_MmDeviceProperty_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ratatosk.mmrest.data.MmAnywhere.internal_static_org_ratatosk_mmrest_data_MmDeviceProperty_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string propertyId = 1;
    public static final int PROPERTYID_FIELD_NUMBER = 1;
    private java.lang.Object propertyId_;
    public boolean hasPropertyId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPropertyId() {
      java.lang.Object ref = propertyId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          propertyId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPropertyIdBytes() {
      java.lang.Object ref = propertyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        propertyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string propertyValue = 2;
    public static final int PROPERTYVALUE_FIELD_NUMBER = 2;
    private java.lang.Object propertyValue_;
    public boolean hasPropertyValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPropertyValue() {
      java.lang.Object ref = propertyValue_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          propertyValue_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPropertyValueBytes() {
      java.lang.Object ref = propertyValue_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        propertyValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string propertyLabel = 3;
    public static final int PROPERTYLABEL_FIELD_NUMBER = 3;
    private java.lang.Object propertyLabel_;
    public boolean hasPropertyLabel() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getPropertyLabel() {
      java.lang.Object ref = propertyLabel_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          propertyLabel_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPropertyLabelBytes() {
      java.lang.Object ref = propertyLabel_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        propertyLabel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string propertyType = 4;
    public static final int PROPERTYTYPE_FIELD_NUMBER = 4;
    private java.lang.Object propertyType_;
    public boolean hasPropertyType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getPropertyType() {
      java.lang.Object ref = propertyType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          propertyType_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPropertyTypeBytes() {
      java.lang.Object ref = propertyType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        propertyType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string propertyUrl = 5;
    public static final int PROPERTYURL_FIELD_NUMBER = 5;
    private java.lang.Object propertyUrl_;
    public boolean hasPropertyUrl() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public String getPropertyUrl() {
      java.lang.Object ref = propertyUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          propertyUrl_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPropertyUrlBytes() {
      java.lang.Object ref = propertyUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        propertyUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      propertyId_ = "";
      propertyValue_ = "";
      propertyLabel_ = "";
      propertyType_ = "";
      propertyUrl_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasPropertyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPropertyValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPropertyLabel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPropertyType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPropertyUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPropertyIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPropertyValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getPropertyLabelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getPropertyTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getPropertyUrlBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPropertyIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPropertyValueBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getPropertyLabelBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getPropertyTypeBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getPropertyUrlBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.ratatosk.mmrest.data.MmAnywhere.MmDevicePropertyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ratatosk.mmrest.data.MmAnywhere.internal_static_org_ratatosk_mmrest_data_MmDeviceProperty_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ratatosk.mmrest.data.MmAnywhere.internal_static_org_ratatosk_mmrest_data_MmDeviceProperty_fieldAccessorTable;
      }
      
      // Construct using org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        propertyId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        propertyValue_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        propertyLabel_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        propertyType_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        propertyUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.getDescriptor();
      }
      
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty getDefaultInstanceForType() {
        return org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.getDefaultInstance();
      }
      
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty build() {
        org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty buildPartial() {
        org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty result = new org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.propertyId_ = propertyId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.propertyValue_ = propertyValue_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.propertyLabel_ = propertyLabel_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.propertyType_ = propertyType_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.propertyUrl_ = propertyUrl_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty) {
          return mergeFrom((org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty other) {
        if (other == org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.getDefaultInstance()) return this;
        if (other.hasPropertyId()) {
          setPropertyId(other.getPropertyId());
        }
        if (other.hasPropertyValue()) {
          setPropertyValue(other.getPropertyValue());
        }
        if (other.hasPropertyLabel()) {
          setPropertyLabel(other.getPropertyLabel());
        }
        if (other.hasPropertyType()) {
          setPropertyType(other.getPropertyType());
        }
        if (other.hasPropertyUrl()) {
          setPropertyUrl(other.getPropertyUrl());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasPropertyId()) {
          
          return false;
        }
        if (!hasPropertyValue()) {
          
          return false;
        }
        if (!hasPropertyLabel()) {
          
          return false;
        }
        if (!hasPropertyType()) {
          
          return false;
        }
        if (!hasPropertyUrl()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              propertyId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              propertyValue_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              propertyLabel_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              propertyType_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              propertyUrl_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string propertyId = 1;
      private java.lang.Object propertyId_ = "";
      public boolean hasPropertyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPropertyId() {
        java.lang.Object ref = propertyId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          propertyId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPropertyId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        propertyId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPropertyId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        propertyId_ = getDefaultInstance().getPropertyId();
        onChanged();
        return this;
      }
      void setPropertyId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        propertyId_ = value;
        onChanged();
      }
      
      // required string propertyValue = 2;
      private java.lang.Object propertyValue_ = "";
      public boolean hasPropertyValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPropertyValue() {
        java.lang.Object ref = propertyValue_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          propertyValue_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPropertyValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        propertyValue_ = value;
        onChanged();
        return this;
      }
      public Builder clearPropertyValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        propertyValue_ = getDefaultInstance().getPropertyValue();
        onChanged();
        return this;
      }
      void setPropertyValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        propertyValue_ = value;
        onChanged();
      }
      
      // required string propertyLabel = 3;
      private java.lang.Object propertyLabel_ = "";
      public boolean hasPropertyLabel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getPropertyLabel() {
        java.lang.Object ref = propertyLabel_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          propertyLabel_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPropertyLabel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        propertyLabel_ = value;
        onChanged();
        return this;
      }
      public Builder clearPropertyLabel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        propertyLabel_ = getDefaultInstance().getPropertyLabel();
        onChanged();
        return this;
      }
      void setPropertyLabel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        propertyLabel_ = value;
        onChanged();
      }
      
      // required string propertyType = 4;
      private java.lang.Object propertyType_ = "";
      public boolean hasPropertyType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getPropertyType() {
        java.lang.Object ref = propertyType_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          propertyType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPropertyType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        propertyType_ = value;
        onChanged();
        return this;
      }
      public Builder clearPropertyType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        propertyType_ = getDefaultInstance().getPropertyType();
        onChanged();
        return this;
      }
      void setPropertyType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        propertyType_ = value;
        onChanged();
      }
      
      // required string propertyUrl = 5;
      private java.lang.Object propertyUrl_ = "";
      public boolean hasPropertyUrl() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getPropertyUrl() {
        java.lang.Object ref = propertyUrl_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          propertyUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPropertyUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        propertyUrl_ = value;
        onChanged();
        return this;
      }
      public Builder clearPropertyUrl() {
        bitField0_ = (bitField0_ & ~0x00000010);
        propertyUrl_ = getDefaultInstance().getPropertyUrl();
        onChanged();
        return this;
      }
      void setPropertyUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        propertyUrl_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:org.ratatosk.mmrest.data.MmDeviceProperty)
    }
    
    static {
      defaultInstance = new MmDeviceProperty(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.ratatosk.mmrest.data.MmDeviceProperty)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ratatosk_mmrest_data_MmDevicesListing_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ratatosk_mmrest_data_MmDevicesListing_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ratatosk_mmrest_data_MmDeviceListing_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ratatosk_mmrest_data_MmDeviceListing_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ratatosk_mmrest_data_MmDeviceProperty_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ratatosk_mmrest_data_MmDeviceProperty_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020MmAnywhere.proto\022\030org.ratatosk.mmrest." +
      "data\"W\n\020MmDevicesListing\022C\n\020mmDeviceList" +
      "ings\030\001 \003(\0132).org.ratatosk.mmrest.data.Mm" +
      "DeviceListing\"\247\001\n\017MmDeviceListing\022\020\n\010dev" +
      "iceId\030\001 \002(\t\022\023\n\013deviceLabel\030\002 \002(\t\022\022\n\ndevi" +
      "ceType\030\003 \002(\t\022\021\n\tdeviceUrl\030\004 \002(\t\022F\n\022mmDev" +
      "iceProperties\030\005 \003(\0132*.org.ratatosk.mmres" +
      "t.data.MmDeviceProperty\"\177\n\020MmDevicePrope" +
      "rty\022\022\n\npropertyId\030\001 \002(\t\022\025\n\rpropertyValue" +
      "\030\002 \002(\t\022\025\n\rpropertyLabel\030\003 \002(\t\022\024\n\014propert",
      "yType\030\004 \002(\t\022\023\n\013propertyUrl\030\005 \002(\t*Q\n\017MmPr" +
      "opertyTypes\022\r\n\tUNDEFINED\020\000\022\013\n\007BOOLEAN\020\001\022" +
      "\013\n\007INTEGER\020\002\022\t\n\005FLOAT\020\003\022\n\n\006STRING\020\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_ratatosk_mmrest_data_MmDevicesListing_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_ratatosk_mmrest_data_MmDevicesListing_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_ratatosk_mmrest_data_MmDevicesListing_descriptor,
              new java.lang.String[] { "MmDeviceListings", },
              org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing.class,
              org.ratatosk.mmrest.data.MmAnywhere.MmDevicesListing.Builder.class);
          internal_static_org_ratatosk_mmrest_data_MmDeviceListing_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_ratatosk_mmrest_data_MmDeviceListing_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_ratatosk_mmrest_data_MmDeviceListing_descriptor,
              new java.lang.String[] { "DeviceId", "DeviceLabel", "DeviceType", "DeviceUrl", "MmDeviceProperties", },
              org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.class,
              org.ratatosk.mmrest.data.MmAnywhere.MmDeviceListing.Builder.class);
          internal_static_org_ratatosk_mmrest_data_MmDeviceProperty_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_ratatosk_mmrest_data_MmDeviceProperty_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_ratatosk_mmrest_data_MmDeviceProperty_descriptor,
              new java.lang.String[] { "PropertyId", "PropertyValue", "PropertyLabel", "PropertyType", "PropertyUrl", },
              org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.class,
              org.ratatosk.mmrest.data.MmAnywhere.MmDeviceProperty.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
